# Generated by Django 3.0.8 on 2020-09-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('cartgory', models.CharField(default='', max_length=50)),
                ('subcartgory', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('decs', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/img')),
            ],
        ),
    ]
