# Generated by Django 3.0.8 on 2020-10-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_relprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timage',
            field=models.ImageField(default='', upload_to='shop/img'),
        ),
    ]
